# Generated by Django 4.0.2 on 2022-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(max_length=500)),
                ('avg_speed', models.IntegerField(max_length=255)),
                ('engine_status', models.CharField(max_length=100)),
                ('fuel_level', models.CharField(max_length=100)),
                ('temp', models.IntegerField(max_length=255)),
            ],
        ),
    ]
